### ISSUE TITLE
Memos should be an array not a string

### ISSUE THREAD

**Issue by stanleyjones** [liftedinit/alberto#109]
From Malcolm:

> Just tried to do a test transaction for an investor who is exercising his tokens, and got this error…

![Image](https://user-images.githubusercontent.com/405258/222004498-e63079ad-82f8-4659-b5a7-628dad10998b.png)

The problem seems to be in the front-end (both ManyJS and Alberto) expecting `memo` to be a string instead of an array of strings.

See Hans' initial PR here: https://github.com/liftedinit/many-js/pull/95

**Comment by fmorency** [comment]
We can deploy alberto automatically now!
