### ISSUE TITLE
Disable `Hardware Authenticator` entry if neighborhood doesn't support it

### ISSUE THREAD

**Issue by fmorency** [liftedinit/alberto#135]
Some neighborhood, such as kvstore, dweb and compute, don't implement the `idstore` module. We should disable the ability to create/import `Hardware Authenticator` when such a neighborhood is selected.

We should also display a message if a neighborhood doesn't support the HSM feature.

@stanleyjones

**Comment by stanleyjones** [comment]
Any objections to applying the same approach as liftedinit/gwen#75 ?

**Comment by fmorency** [comment]
> Any objections to applying the same approach as [liftedinit/gwen#75](https://github.com/liftedinit/gwen/pull/75) ?

No objection, sounds good.
