### ISSUE TITLE
MS Edge user should be able to create a hardware account

### ISSUE THREAD

**Issue by stanleyjones** [liftedinit/alberto#99]
From Slack (https://liftedinit.slack.com/archives/C02C91EMFDK/p1669833507384309):

> Hey Lifted team! I have an Alberto wallet-specific question...not sure where to put it so putting it in [#general](https://liftedinit.slack.com/archives/C02C91EMFDK) I'm currently helping node owners create their wallet with HSMs...but one NP is having trouble getting his windows laptop to recognize the ledger device during the Alberto account creation process...nothing happens at this point and the request times out. (we've DL'ed FIDO U2F)

OS: Windows
Browser: Edge (?)

> Update: a second user with a Ledger and Windows machine cannot get past the external security key prompt in creating an account on Alberto.

Current wallet setup instructions:
[Lifted Node Program_ Wallet Setup.pdf](https://github.com/liftedinit/alberto/files/10142009/Lifted.Node.Program_.Wallet.Setup.pdf)

**Comment by stanleyjones** [comment]
I was able to create an account using MS Edge with my Trezor. Looking for someone with a Ledger who can take over this bug since I can’t reproduce.

**Comment by rfisch** [comment]
I'm setting up Parallels today and will test Windows -> Edge with Ledger Nano S Plus

**Comment by rfisch** [comment]
I have successfully restore my wallet in both Edge and Chrome browsers on Windows 11 v22H2 (osbuild 22621.525)

**Comment by tysloan** [comment]
I was able to create an account using Microsoft Edge, Firefox, and Chrome on Windows 11 with a Ledger Nano X. 

The behavior of timing out did occur if I did not click my Fido U2F app on my Ledger and then click again to "Register Unknown". It could be that the described issues are occurring for users if they are not clicking their Ledger to authenticate when presented with the prompt to connect.

**Comment by rfisch** [comment]
I'm going to mark this as complete, since we were unable to replicate the behavior.  I would suggest we add screen recording as a feature, or at least have any LIfted rep working with a customer having an issue try and get screen captures or recordings.  There are pop-ups on windows that are not modal and that quickly get hidden under window stacks.  This happen to me a few times as the USB acceptance was buried, but once I saw that and approved everything worked as expected.
